"""
Centralized configuration for the AI/Ollama pipeline.
"""

# ============================================================
# Ollama Connection
# ============================================================

OLLAMA_URL = "http://localhost:11434/api/generate"

OLLAMA_MODEL = "llama3:latest"

OLLAMA_TIMEOUT = 60


# ============================================================
# Ollama Generation Parameters
# ============================================================

# 0.0 gives deterministic and consistent responses.
OLLAMA_TEMPERATURE = 0.0

# Controls probability sampling.
OLLAMA_TOP_P = 1.0


# ============================================================
# Ollama Context / Output Limits
# ============================================================

# Maximum context window used by the Ollama request.
OLLAMA_NUM_CTX = 4096

# Maximum number of tokens generated by the model.
OLLAMA_NUM_PREDICT = 512


# ============================================================
# Input Context Safety
# ============================================================

# Maximum source-code characters sent to the AI model.
#
# Large scanner findings can otherwise create oversized
# prompts and consume the available model context.
MAX_CODE_LENGTH = 12000